### ISSUE TITLE
Chat Prefix

### ISSUE THREAD

**Issue by TheDarthFather** [xDefcon/spigot-ping#7]
Hi,
I am using this with essentials and tried to add %ping% or {%ping%} to the chat essentials format, but I get this in the console.
Am I missing something ? 

[20:23:22 ERROR]: Could not pass event AsyncPlayerChatEvent to EssentialsChat v2.19.0
java.util.UnknownFormatConversionException: Conversion = 'p'
        at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:105) ~[patched_1.17.1.jar:git-Paper-266]
        at com.earth2me.essentials.chat.EssentialsChatPlayerListenerLowest.onPlayerChat(EssentialsChatPlayerListenerLowest.java:69) ~[EssentialsXChat-2.19.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor277.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-266]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-266]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-266]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) [patched_1.17.1.jar:git-Paper-266]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:234) [patched_1.17.1.jar:git-Paper-266]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:116) [patched_1.17.1.jar:git-Paper-266]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65) [patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2174) [patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2085) [patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2051) [patched_1.17.1.jar:git-Paper-266]
        at net.minecraft.network.protocol.game.PacketPlayInChat$1.run(PacketPlayInChat.java:40) [patched_1.17.1.jar:git-Paper-266]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?

**Comment by xDefcon** [comment]
Hello,
Unfortunately this plugin does not come with chat placeholder support, you might want to install PlaceholderAPI and use the %player_ping% placeholder to display player's ping.

**Comment by TheDarthFather** [comment]
Thanks,
I installed the PlaceholderAPI  and the player "addon" .. but i get the same message.
Is this suppose to work like this (esentials chat setup)?
format: '%player_ping% {DISPLAYNAME}&r &7{SUFFIX}&r: {MESSAGE}' 

Later Edit: Seems I need ChatInjector as well ...
